import java.awt.BorderLayout;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JPanel;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.data.time.Millisecond;
import org.jfree.data.time.TimeSeries;
import org.jfree.data.time.TimeSeriesCollection;

public class Main extends javax.swing.JFrame
{
    private static Main instance;
    private Main() 
    {
        initComponents();
    }
    
    public static Main getInstance()
    {
        if(instance==null)
        {
            instance= new Main();
        }
        return instance;
    }
    
   private void initJPanel()
   {
       jPanel1.setLayout(new BorderLayout());
   }
    
   public void  setTextLeq(String txtLeq)
   {
       this.txtLeq.setText(txtLeq);
   }
   
   public void setChartPanel(ChartPanel cp)
   {
     jPanel1.add(cp);   
     jPanel1.validate();
   }
   
   public JPanel getJPanel1()
   {
       return jPanel1;
   }
   
   public void  setTextStartTime(double txtStartTime)
   {
       String txt = new Converter().msToDate(txtStartTime);
       this.txtStartTime.setText(txt);
   }
      
    public void  setTextStopTime(double txtStopTime)
   {
       String txt = new Converter().msToDate(txtStopTime);
       this.txtStopTime.setText(txt);
   }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jPanel1 = new javax.swing.JPanel();
        txtLeq = new javax.swing.JTextField();
        lbLeq = new javax.swing.JLabel();
        btnLoadData = new javax.swing.JButton();
        lbStartTime = new javax.swing.JLabel();
        txtStopTime = new javax.swing.JTextField();
        lbStopTime = new javax.swing.JLabel();
        txtStartTime = new javax.swing.JTextField();
        sprAutoMarker = new javax.swing.JSpinner();
        btnAutoMarker = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        listOfMarker = new javax.swing.JPanel();

        jMenuItem1.setText("jMenuItem1");

        jButton1.setText("jButton1");

        jButton3.setText("jButton3");

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.CROSSHAIR_CURSOR));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 896, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 385, Short.MAX_VALUE)
        );

        txtLeq.setText("Load data");
        txtLeq.setEnabled(false);
        txtLeq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLeqActionPerformed(evt);
            }
        });

        lbLeq.setText("LAeq");

        btnLoadData.setText("Wczytaj dane");
        btnLoadData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoadDataActionPerformed(evt);
            }
        });

        lbStartTime.setText("Start time");

        txtStopTime.setText("stop time");
        txtStopTime.setEnabled(false);
        txtStopTime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStopTimeActionPerformed(evt);
            }
        });

        lbStopTime.setText("Stop time");

        txtStartTime.setText("start time");
        txtStartTime.setEnabled(false);
        txtStartTime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStartTimeActionPerformed(evt);
            }
        });

        btnAutoMarker.setText("AutoMarker");
        btnAutoMarker.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAutoMarkerActionPerformed(evt);
            }
        });

        listOfMarker.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout listOfMarkerLayout = new javax.swing.GroupLayout(listOfMarker);
        listOfMarker.setLayout(listOfMarkerLayout);
        listOfMarkerLayout.setHorizontalGroup(
            listOfMarkerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 179, Short.MAX_VALUE)
        );
        listOfMarkerLayout.setVerticalGroup(
            listOfMarkerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(listOfMarker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(listOfMarker, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(sprAutoMarker, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAutoMarker, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(151, 151, 151)
                        .addComponent(lbLeq)
                        .addGap(0, 0, 0)
                        .addComponent(txtLeq, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnLoadData, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 1, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lbStopTime))
                            .addComponent(lbStartTime, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtStartTime, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtStopTime, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtLeq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbLeq)
                            .addComponent(btnLoadData))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lbStartTime)
                                .addComponent(txtStartTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtStopTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lbStopTime))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(sprAutoMarker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAutoMarker))))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jPanel1.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtLeqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLeqActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLeqActionPerformed
    /**
     * If between data exist gap, insert time between data and set null value for leq
     * @param time
     * @param leq
     * @return 
     */
    private ArrayList<ArrayList<Double>> getArrayWithoutGap(ArrayList<Double> time, ArrayList<Double> leq)
    {
        ArrayList<Double> tmpTime = time;
        ArrayList<Double> tmpLeq = leq;
        ArrayList<ArrayList<Double>> timeAndLeq = new ArrayList<>();
        ArrayList<Integer> idxToAdd = new ArrayList<>();
        Double tmpStartTime;
        double tm1;
        double tm2;
        int tmSize;
        double tmpDouble;
        
        int sizeOfArray = time.size();
        for(int i=0;i<(sizeOfArray-1);i++){
            
            tmpDouble = time.get(i);
            tm1 = new Converter().roundMs(tmpDouble);
            tmpDouble = time.get(i+1);
            tm2 = new Converter().roundMs(tmpDouble);
            
            if((tm1+1000)!=(tm2))
            {
                tmSize = (int)(tm2 - tm1)/1000;
                for(int j=i;j<(tmSize+i)-1;j++){
                    idxToAdd.add(j+1);
                }
            }
        }
        
        tmpStartTime = time.get(Constant.IDX_DATE);
        for(var idx:idxToAdd)
        {
            tmpTime.add(idx,tmpStartTime+idx*1000);
            tmpLeq.add(idx,null);
            //Add here flags too;
        }
        
        //Add here flags too;
        timeAndLeq.add(tmpTime);
        timeAndLeq.add(tmpLeq);
        
        return timeAndLeq;
    }
    
    /**
     * Create Time series and check if few time series have gap
     * @param time
     * @param leq
     * @return 
     */
    private TimeSeries getTimeSeries(ArrayList<Double> time,ArrayList<Double> leq)
    {
        return new DataMeterTs().getTimeSeries(time, leq);
    }
    
    private ArrayList<ArrayList<Double>> getMergedArray(ArrayList<ArrayList<Double>> time, ArrayList<ArrayList<Double>> leq)
    {
        ArrayList<ArrayList<Double>> tmpTimeAndLeq = new ArrayList<>();
        ArrayList<Double> tmpTime = new ArrayList<>();
        ArrayList<Double> tmpLeq = new ArrayList<>();
        
        int sizeA = time.size();
        int sizeB;
        
        for(int i=0;i<sizeA;i++)
        {
            sizeB = time.get(i).size();
            for(int j=0;j<sizeB;j++)
            {
                tmpTime.add(time.get(i).get(j));
                tmpLeq.add(leq.get(i).get(j));
            }
        }
        
        tmpTimeAndLeq.add(tmpTime);
        tmpTimeAndLeq.add(tmpLeq);
        
        return tmpTimeAndLeq;
    }
    
    /**
     * Get array of time nad Leq and put in in JPanel
     * @param arrayOfarray 
     */
    ChartPanel setDataToJPanel()
    {
    var timeArray = DataMeter.getInstance().getArrayOfDate();
    var leqArray = DataMeter.getInstance().getArrayOfLeq();
    var mergedArray = getMergedArray(timeArray, leqArray);
    var awg = getArrayWithoutGap(mergedArray.get(Constant.IDX_DATE), mergedArray.get(Constant.IDX_LEQ));
    TimeSeries ts = getTimeSeries(awg.get(Constant.IDX_DATE), awg.get(Constant.IDX_LEQ));
    TimeSeriesCollection tsc = new DataMeterTsc().getAndsetTimeSeriesCollection(ts);
     JFreeChart jfc = new ChartJfreeChart().getJFreeChart(tsc);
    ChartPanel cp = ChartPnl.getInstance().getChartPanel(jfc);
    cp.setRangeZoomable(true);
    cp.setDomainZoomable(true);
    
    jPanel1.setLayout(new BorderLayout());
    jPanel1.add(cp,BorderLayout.CENTER);
    jPanel1.validate();
    return cp;
    }
    
    private ArrayList<ArrayList<Double>> getDataTroughtAdapter(DMEnvironment enviormentNoise)
    {
       ArrayList<String[]> arrayFromMeter = enviormentNoise.getCSVFromFile();
       ArrayList<Double> dataArray = enviormentNoise.getDateArray(arrayFromMeter);
       ArrayList<Double> leqArray = enviormentNoise.getLeqArray(arrayFromMeter);
       ArrayList<ArrayList<Double>> array = new ArrayList<>();
       array.add(dataArray);
       array.add(leqArray);
       return array;
    }
    
    private void setMouseListener(ChartPanel cp)
    {
       cp.addMouseListener(new MouseMarker(cp));
    }
    
    private void btnLoadDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoadDataActionPerformed
        DMEnvironment enviormentNoise = new DMAdapter958v1();
        ArrayList<ArrayList<Double>> dateAndLeqFromAdapter = getDataTroughtAdapter(enviormentNoise);
        new DataFlags().setFlagsArray(dateAndLeqFromAdapter);
        ChartPanel cp = setDataToJPanel();
        ChartMarker.getInstance().initialization(cp);
        setMouseListener(cp);
        new Calculation().updateLeq();
    }//GEN-LAST:event_btnLoadDataActionPerformed

    private void txtStopTimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStopTimeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStopTimeActionPerformed

    private void txtStartTimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStartTimeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStartTimeActionPerformed

    private void btnAutoMarkerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAutoMarkerActionPerformed
        int autoMarker = sprAutoMarker.getValue().hashCode();
        new DataFlags().setFlagsMarker(autoMarker);
        ChartMarker.getInstance().setFlagsMarker(autoMarker);
        new Calculation().updateLeq();
    }//GEN-LAST:event_btnAutoMarkerActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               var mainForm =  Main.getInstance();
               mainForm.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAutoMarker;
    private javax.swing.JButton btnLoadData;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbLeq;
    private javax.swing.JLabel lbStartTime;
    private javax.swing.JLabel lbStopTime;
    private javax.swing.JPanel listOfMarker;
    private javax.swing.JSpinner sprAutoMarker;
    private javax.swing.JTextField txtLeq;
    private javax.swing.JTextField txtStartTime;
    private javax.swing.JTextField txtStopTime;
    // End of variables declaration//GEN-END:variables
}